package com.mihail.suppubot.entity;

public enum ChatStatus {
    START,
    SENDING_NUMBER,
    MAKING_CALL_REQUEST_1_NUMBER,
    MAKING_CALL_REQUEST_2_NAME,
    GETTING_CONTACTS,
    GETTING_ORDERS,
    GETTING_ORDER_STATUS,
    GETTING_ORDER_STATUS_BY_RECEIPT,
    GETTING_ORDER_STATUS_BY_PHONE,
    HAVE_AN_INCIDENT


}
